### ISSUE TITLE
相機位置資料初始呈現有誤

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-webapp#188]
### 問題簡述
![Screenshot 2019-04-12 20 12 52](https://user-images.githubusercontent.com/31983251/56037311-8b318500-5d61-11e9-975a-1d415247feb1.png)

- [ ] 至樣區內選定相機位置後，初始資料載入完成時分頁計數不是停在第一頁。
- [ ] 上方篩選選單初始應對應至該相機位置之資料範圍

### 重現步驟

1. 連結 https://dev.camera-trap.tw/#/project/60c5ad24-1181-46b2-89a5-cd264d852c59/site/%E7%BE%85%E6%9D%B1%E8%99%95/NULL
2. 在相機位置處選取「查看更多」，選取相機位置 LD88B
3. 等待紀錄載入
...

### 預期行為

1. 頁數顯示 1/220
2. 日期輸入框顯示 2015-08-16 及 2015-09-14

### 實際行為

1. 頁數顯示 179/220
2. 日期輸入框顯示 2001-01-01 及 2018-12-31

## 錯誤或提示訊息

```
webpack-internal:///./node_modules/moment/moment.js:292 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2001/1/1, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.eval [as createFromInputFallback] (webpack-internal:///./node_modules/moment/moment.js:319:98)
    at configFromString (webpack-internal:///./node_modules/moment/moment.js:2367:15)
    at configFromInput (webpack-internal:///./node_modules/moment/moment.js:2593:13)
    at prepareConfig (webpack-internal:///./node_modules/moment/moment.js:2576:13)
    at createFromConfig (webpack-internal:///./node_modules/moment/moment.js:2543:44)
    at createLocalOrUTC (webpack-internal:///./node_modules/moment/moment.js:2630:16)
    at createLocal (webpack-internal:///./node_modules/moment/moment.js:2634:16)
    at hooks (webpack-internal:///./node_modules/moment/moment.js:11:29)
    at eval (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/pages/index/views/Site.vue?vue&type=script&lang=js&:537:72)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/pages/index/views/Site.vue?vue&type=script&lang=js& (https://dev.camera-trap.tw/5.js:71:1)
warn @ webpack-internal:///./node_modules/moment/moment.js:292
```
### 作業環境
**作業系統及版本：**
<pre><code>
macOS 10.14.4
</code></pre>

**瀏覽器及版本：**
<pre><code>
Chrome Version 73.0.3683.103 (Official Build) (64-bit)
</code></pre>

**Comment by diabloevagto** [comment]
revert #167 PR 後不會有此問題
